// AUTO-GENERATED from amib.lst (64tass listing) — do not edit by hand.
// One entry per source line of A Mind Is Born, comments stripped.
//   k: equ|data|code|label|gap   t: source text   c: zero-page cell it assembles to (for the live heat highlight)
export const SRC = [
  {k:"equ", t:"vmptr      = $cb"},
  {k:"equ", t:"clock      = $13"},
  {k:"equ", t:"clock_msb  = $20"},
  {k:"equ", t:"script     = $21"},
  {k:"equ", t:"const_d3ff = $03"},
  {k:"equ", t:"const_d01c = $0f"},
  {k:"equ", t:"mel_lfsr   = $14"},
  {k:"equ", t:"sid        = $0a"},
  {k:"equ", t:"mod_op1    = $d5"},
  {k:"equ", t:"mod_op2    = $d7"},
  {k:"equ", t:"basstbl    = $f3"},
  {k:"equ", t:"freqtbl    = $f7"},
  {k:"gap"},
  {k:"data", c:0x01, t:"  .byte $0D,$08"},
  {k:"data", c:0x03, t:"  .byte $FF,$D3"},
  {k:"data", c:0x05, t:"  .byte $9E,$32,$32,$32,$35"},
  {k:"data", c:0x0a, t:"  .byte $00"},
  {k:"data", c:0x0b, t:"  .byte $00"},
  {k:"data", c:0x0c, t:"  .byte $00"},
  {k:"data", c:0x0d, t:"  .byte $19"},
  {k:"data", c:0x0e, t:"  .byte $41"},
  {k:"data", c:0x0f, t:"  .byte $1C"},
  {k:"data", c:0x10, t:"  .byte $D0"},
  {k:"data", c:0x11, t:"  .byte $00"},
  {k:"data", c:0x12, t:"  .byte $DC"},
  {k:"data", c:0x13, t:"  .byte $00"},
  {k:"data", c:0x14, t:"  .byte $00"},
  {k:"data", c:0x15, t:"  .byte $11"},
  {k:"data", c:0x16, t:"  .byte $D0"},
  {k:"data", c:0x17, t:"  .byte $E0"},
  {k:"data", c:0x18, t:"  .byte $0B"},
  {k:"data", c:0x19, t:"  .byte $10"},
  {k:"data", c:0x1a, t:"  .byte $33"},
  {k:"data", c:0x1b, t:"  .byte $0E"},
  {k:"data", c:0x1c, t:"  .byte $61"},
  {k:"data", c:0x1d, t:"  .byte $90"},
  {k:"data", c:0x1e, t:"  .byte $F5"},
  {k:"data", c:0x1f, t:"  .byte $07"},
  {k:"data", c:0x20, t:"  .byte $00"},
  {k:"data", c:0x21, t:"  .byte $FF"},
  {k:"data", c:0x22, t:"  .byte $1F"},
  {k:"data", c:0x23, t:"  .byte $14,$41"},
  {k:"data", c:0x25, t:"  .byte $D5,$24"},
  {k:"data", c:0x27, t:"  .byte $15,$25"},
  {k:"data", c:0x29, t:"  .byte $15,$53"},
  {k:"data", c:0x2b, t:"  .byte $15,$61"},
  {k:"data", c:0x2d, t:"  .byte $D5,$29"},
  {k:"data", c:0x2f, t:"  .byte $1B,$0F"},
  {k:"gap"},
  {k:"code", c:0x31, t:"  inc     clock"},
  {k:"code", c:0x33, t:"  inc     clock"},
  {k:"code", c:0x35, t:"  bne     noc1"},
  {k:"code", c:0x37, t:"  inc     clock_msb"},
  {k:"gap"},
  {k:"label", t:"noc1"},
  {k:"code", c:0x39, t:"  lda     #$61"},
  {k:"code", c:0x3b, t:"  sta     sid+2*7+4"},
  {k:"code", c:0x3d, t:"  lax     clock_msb"},
  {k:"code", c:0x3f, t:"  cpx     #$3f"},
  {k:"code", c:0x41, t:"  beq     highpass"},
  {k:"code", c:0x43, t:"  bcc     noend"},
  {k:"code", c:0x45, t:"  lsr     $d011"},
  {k:"code", c:0x48, t:"  jmp     ($fffc)"},
  {k:"gap"},
  {k:"label", t:"highpass"},
  {k:"code", c:0x4b, t:"  ldy     #$6d"},
  {k:"code", c:0x4d, t:"  sty     sid+$18"},
  {k:"code", c:0x4f, t:"  sty     mod_op2"},
  {k:"gap"},
  {k:"label", t:"noend"},
  {k:"code", c:0x51, t:"  lsr"},
  {k:"code", c:0x52, t:"  asr     #$1c"},
  {k:"code", c:0x54, t:"  tay"},
  {k:"code", c:0x55, t:"  lda     clock"},
  {k:"code", c:0x57, t:"  and     #$30"},
  {k:"code", c:0x59, t:"  bne     noduck"},
  {k:"code", c:0x5b, t:"  dec     sid+2*7+4"},
  {k:"gap"},
  {k:"label", t:"noduck"},
  {k:"code", c:0x5d, t:"  cpx     #$2f"},
  {k:"code", c:0x5f, t:"  beq     bassoff"},
  {k:"code", c:0x61, t:"  bcs     nointro"},
  {k:"code", c:0x63, t:"  ldx     #2"},
  {k:"gap"},
  {k:"label", t:"nointro"},
  {k:"code", c:0x65, t:"  cmp     #$10"},
  {k:"code", c:0x67, t:"  beq     bassoff"},
  {k:"code", c:0x69, t:"  txa"},
  {k:"code", c:0x6a, t:"  and     #3"},
  {k:"code", c:0x6c, t:"  tax"},
  {k:"code", c:0x6d, t:"  lda     basstbl,x"},
  {k:"code", c:0x6f, t:"  sta     sid+0*7+0"},
  {k:"gap"},
  {k:"data", c:0x71, t:"  .byte    $2d"},
  {k:"gap"},
  {k:"label", t:"bassoff"},
  {k:"code", c:0x72, t:"  lax     #0"},
  {k:"code", c:0x74, t:"  bcs     bassdone"},
  {k:"code", c:0x76, t:"  lax     script+1,y"},
  {k:"code", c:0x78, t:"  ldx     script,y"},
  {k:"code", c:0x7a, t:"  sta     0,x"},
  {k:"code", c:0x7c, t:"  lda     clock"},
  {k:"code", c:0x7e, t:"  asr     #$0e"},
  {k:"code", c:0x80, t:"  tax"},
  {k:"code", c:0x81, t:"  sbx     #256-8"},
  {k:"code", c:0x83, t:"  stx     vmptr+1"},
  {k:"code", c:0x85, t:"  eor     #$07"},
  {k:"gap"},
  {k:"label", t:"bassdone"},
  {k:"code", c:0x87, t:"  sta     sid+0*7+1"},
  {k:"code", c:0x89, t:"  lda     clock"},
  {k:"code", c:0x8b, t:"  and     #$0f"},
  {k:"code", c:0x8d, t:"  bne     nomel"},
  {k:"code", c:0x8f, t:"  lda     #$b8"},
  {k:"code", c:0x91, t:"  sre     mel_lfsr"},
  {k:"code", c:0x93, t:"  bcc     noc2"},
  {k:"code", c:0x95, t:"  sta     mel_lfsr"},
  {k:"gap"},
  {k:"label", t:"noc2"},
  {k:"code", c:0x97, t:"  and     #7"},
  {k:"code", c:0x99, t:"  tax"},
  {k:"code", c:0x9a, t:"  lda     freqtbl,x"},
  {k:"code", c:0x9c, t:"  sta     sid+1*7+1"},
  {k:"gap"},
  {k:"label", t:"nomel"},
  {k:"code", c:0x9e, t:"  ldy     #8"},
  {k:"gap"},
  {k:"label", t:"vicloop"},
  {k:"code", c:0xa0, t:"  lax     sid+3,y"},
  {k:"code", c:0xa2, t:"  sta     (const_d01c),y"},
  {k:"code", c:0xa4, t:"  dey"},
  {k:"code", c:0xa5, t:"  bpl     vicloop"},
  {k:"code", c:0xa7, t:"  tay"},
  {k:"gap"},
  {k:"label", t:"loop"},
  {k:"code", c:0xa8, t:"  lax     sid-1,y"},
  {k:"code", c:0xaa, t:"  sta     (const_d3ff),y"},
  {k:"code", c:0xac, t:"  dey"},
  {k:"code", c:0xad, t:"  bne     loop"},
  {k:"code", c:0xaf, t:"  jmp     $ea7e"},
  {k:"code", c:0xb2, t:"  sei"},
  {k:"code", c:0xb3, t:"  stx     $286"},
  {k:"code", c:0xb6, t:"  stx     $d021"},
  {k:"code", c:0xb9, t:"  jsr     $e544"},
  {k:"code", c:0xbc, t:"  ldx     #$fd"},
  {k:"gap"},
  {k:"label", t:"initloop"},
  {k:"code", c:0xbe, t:"  lda     $802,x"},
  {k:"code", c:0xc1, t:"  sta     $02,x"},
  {k:"code", c:0xc3, t:"  dex"},
  {k:"code", c:0xc4, t:"  bne     initloop"},
  {k:"code", c:0xc6, t:"  stx     $315"},
  {k:"code", c:0xc9, t:"  jmp     $cc"},
  {k:"code", c:0xcc, t:"  lda     #$50"},
  {k:"code", c:0xce, t:"  sta     $d011"},
  {k:"code", c:0xd1, t:"  cli"},
  {k:"gap"},
  {k:"label", t:"mainloop"},
  {k:"code", c:0xd2, t:"  lda     $dc04"},
  {k:"code", c:0xd5, t:"  ldy     #$c3"},
  {k:"code", c:0xd7, t:"  ora     $d41c"},
  {k:"code", c:0xda, t:"  pha"},
  {k:"code", c:0xdb, t:"  asr     #$04"},
  {k:"code", c:0xdd, t:"  ldy     #$30"},
  {k:"code", c:0xdf, t:"  sty     $d018"},
  {k:"code", c:0xe2, t:"  adc     (vmptr),y"},
  {k:"code", c:0xe4, t:"  inc     vmptr"},
  {k:"code", c:0xe6, t:"  adc     (vmptr),y"},
  {k:"code", c:0xe8, t:"  ror"},
  {k:"code", c:0xe9, t:"  ora     clock_msb"},
  {k:"code", c:0xeb, t:"  ldy     #$30+40"},
  {k:"code", c:0xed, t:"  ora     mod_op1"},
  {k:"code", c:0xef, t:"  sta     (vmptr),y"},
  {k:"code", c:0xf1, t:"  bne     mainloop"},
  {k:"gap"},
  {k:"data", c:0xf3, t:"  .byte $2B,$AA,$02,$62"},
  {k:"data", c:0xf7, t:"  .byte $00,$18,$26,$20"},
  {k:"data", c:0xfb, t:"  .byte $12,$24,$13,$10"},
];
